# Build and publish package 

name: dl-aglo-build-manual
run-name: Build & Deploy DL-Algorithms (v${{ inputs.appversion }}) to ${{ github.event.inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        options: 
        - UAT
        - STA
        - TEST
        default: TEST
        description: Target environment    
      appversion:
        type: string  
        required: true
        description: 'Application Version'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          python-version: ["3.10"]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set Up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Extract Version Number
      id: extract_version
      run: echo "{name}={version}::$(echo ${GITHUB_REF#refs/heads/release_})" >> $GITHUB_OUTPUT

    - name: Build Python Package
      run: python setup.py sdist bdist_wheel

    - name: Upload Package to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: DL-Algorithms-${{ inputs.appversion }}-${{ github.event.inputs.environment }}.tar.gz
        path: ./dist


